study1 + assignment1
bradley4/tdd-calculator pull request #1
Opened 2022-01-29 12:33 UTC by kkoon9

2022-01-29 12:35 UTC, kkoon9 commented on build.gradle
> +    testImplementation "org.junit.jupiter:junit-jupiter-params:5.4.2"
ParameterizedTest 사용을 위한 의존성 추가 코드입니다.

2022-01-29 12:35 UTC, kkoon9 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip
제 컴퓨터에서 7.1은 계속 build 오류나서 6.9로 낮춰서 진행했습니다.

2022-01-29 13:32 UTC, bradley4 requested changes
아직 과제 2주 남았는데, 이렇게 빨리 하실줄이야 👍
study까지 안하셔도 됐는데 다하셨네요. 제 기억으로는 테스트가 하나 빠진것같아요~!

고생하셨습니다. 몇가지 생각해볼만한 코멘트를 남겼습니다.

2022-01-29 13:32 UTC, bradley4 commented on build.gradle
> +    testImplementation "org.junit.jupiter:junit-jupiter-params:5.4.2"
제가 다 테스트해봤어야했는데 훌륭합니다 .😀

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +    int plus(String input) {
- 접근 지시자를 붙여보면 어떨까요?
- 이번에 구현해야하는 것은 문자계산기입니다.  다른 개발자가 유지보수를 맡기로 했을때 
   파라미터로 받는 `input`이라는 변수를 보고 어떤 값일지 예상을 할 수 있을까요?
   `textNumbers`같은 표현은 어떨까요? 동의하시나요?

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +        }
- `null`값이 들어오면 어떻게 되나요?
- 공백이 포함된 문자면 어떻게 해야할까요? `"    "`

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +        int[] elements = split(input);
- `element`라는 것을 보고 어떤 값인지 예상하기 힘들 것같습니다!

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +    int[] split(String input) {
기능을 나누는 시도가 좋습니다 👍
계산기의 책임은 `계산`을 하는 것이기때문에 이런 문자 분리 기능은 다른 클래스와 협력하는 것으로 바꿔보면 어떨까요?

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +        String regex = ",|:";
String을 패턴 매칭을 위해 Pattern으로 바꾸는 것은 꽤나 비싼 행위입니다. 미리 Pattern으로 만들어 사용하는 것은 어떨까요? 아래의 글을 참고하세요.
https://stackoverflow.com/questions/2469244/whats-the-difference-between-string-matches-and-matcher-matches/2469275

2022-01-29 13:32 UTC, bradley4 commented on src/test/java/calculator/README.md
> +- [ ] 문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 throw한다.
-[X] 으로 표시하면 알아보기 쉬울 것같아요

2022-01-29 13:32 UTC, bradley4 commented on src/test/java/study/StringTddTest.java
> +        Assertions
이런건 static import를 해주면 가독성이 더 좋아져요

2022-01-29 13:32 UTC, bradley4 commented on src/test/java/study/StringTddTest.java
> +                .containsExactly(1, 2);
디미터 법칙을 제가 말씀드리느랴 예외상황도 설명드려야했는데 제가 못했습니다.
이러한 assertion 같은 경우는 한줄로 쓰는게 가독성이 더 좋습니다.
``` java
assertThat(result).containExactly(1,2);
```

2022-01-29 13:32 UTC, bradley4 commented on src/test/java/study/StringTddTest.java
> +                .hasMessageContaining("index [%d]는 벗어난 인덱스입니다.", index);
👍

2022-01-29 13:32 UTC, bradley4 commented on src/test/java/study/CollectionTddTest.java
> +                .isEqualTo(3);
실습할때 설명드릴려고 했는데, study는 Junit연습을 위한 것이라 굳이 일급컬렉션을 생각하고 만들지 않으셔도 됩니다~!
``` java
    assertThat(numbers.size()).isEqualTo(3);
```
이정도만 해도 충분합니다

2022-01-29 13:32 UTC, bradley4 commented on src/test/java/study/CollectionTddTest.java
> +    }
목록으로 입력받은 값의 포함여부 리턴에 대한 테스트도 있지않았나요?

2022-01-29 13:32 UTC, bradley4 commented on src/test/java/calculator/CalculatorTest.java
> +        Assertions.assertThat(result).isEqualTo(true);
`isTrue()`를 써도 좋을 것같아요~

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +                        .toArray();
- 불필요하게 변수를 만들지 않고 리턴하면 더 좋을 것같습니다!
- 파싱하는 원소가 숫자라는 보장이 있을까요?
- 특별한 이유가 있지않는 이상 `List`를 사용하는게 더 좋을 것같습니다.
> [이텍티브자바-배열보다-리스트를사용하라](https://jyami.tistory.com/92)

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +        String[] inputSplitComma = input.split(",");
하드코딩을 없애보면 어떨까요? 

see also
> https://tecoble.techcourse.co.kr/post/2020-05-07-avoid-hard-coding/

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +    private String cleansingBrackets(String input) {
`cleansing`을 쓰는 것보다 일반적으로 제거의 표현으로 사용하는 `remove`혹은 원의미대로 `subString()`같은 표현을 써보면 다른 개발자들도 이해하기 쉬울 것같습니다.

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +        input = cleansingBrackets(input);
해당코드의 input이 안전할 것이라는 보장은 없습니다.

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +        }
하드코딩을 없애보면 어떨까요?

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +
불필요한 공백은 제거해주세요

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +        checkException(input, regex);
중간중간 변경된 상태를 점거하는 것보다 
변경을하면서 예외를 처리해보면 어떨까요?

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +        String[] inputSplitComma = input.split(regex);
`inputSplitComma`을 보고 어떤 것을 예측할 수 있을까요?

2022-01-29 13:32 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +        return result;
숫자로 안정적으로 변경된다는 보장을 할 수 없습니다.

2022-01-29 13:39 UTC, bradley4 commented on src/test/java/study/StringTddTest.java
> +                .hasMessageContaining("index [%d]는 벗어난 인덱스입니다.", index);
``` java
assertThatThrownBy(() -> stringTdd.charAt(input, index))
                .isInstanceOf(StringIndexOutOfBoundsException.class);
```
이런식으로 써보면 가독성이 더 좋아지지않을까요?

2022-01-29 13:46 UTC, bradley4 commented
커밋로그를 확인해봤는데 기능과 커밋이 일치해서 읽기 좋았어요 💯
기왕 연습이니 PR메시지도 연습을 해보면 어떨까요?

2022-01-29 13:49 UTC, bradley4 commented on src/test/java/calculator/CalculatorTest.java
> +        String input = "1,2";
콜론 테스트는 어디에?

2022-01-29 13:50 UTC, bradley4 commented on src/test/java/calculator/CalculatorTest.java
> +        String input = "//;\n1,2";
음수에 대한 테스트는 어디에? 👀

2022-01-29 13:51 UTC, bradley4 commented on src/test/java/calculator/CalculatorTest.java
> +        String input = "";
`@NullAndEmptySource` 을 찾아보고 적용해보면 어떨까요?

2022-01-30 00:07 UTC, kkoon9 commented on src/main/java/calculator/Calculator.java
> +    int plus(String input) {
`input`보다 직관적인 `textNumbers`으로 변수명을 바꾸는게 좋아보여요!

대니스 접근 지시자에 궁금한 점이 있어서 코멘트 남깁니다!
저는 package-private하게 쓰려고 접근 지시자를 안붙였는데 대니스는 어떤 접근 지시자를 쓰는게 괜찮다고 생각하시나요!?
저는 테스트와 같은 패키지명을 사용하면 public보다는 protected나 default(package-private) 접근 지시자를 사용해도 괜찮다는 생각입니다!
추가로, Calculator 클래스와 CalculatorTest 클래스도 접근 지시자를 public으로 구성하지 않아도 되겠다는 생각을 했습니다!

2022-01-30 00:51 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +    int plus(String input) {
저는 클래스 레벨에서는 특별한 의도(외부접근을 막지 않으면 안된다는지)가 없지않는 이상 `public`으로 두고 있습니다.
다만 테스트 패키지의 Junit5같은 경우에는 public을 사용하지 않아도 되서 default로 두고 있습니다.
일반적으로 개발을 하게되면 굳이 public으로 두고 있습니다.

클래스 내부 레벨인데요. 여기서부터는 내가 알려줄 정보와 알려주지 않을 정보와 생각해봐야합니다. 내가 외부에 공개하고 싶은 정보는 계산기의 덧셈 기능 뿐입니다. `plus`외 `split`은 구현정보는 외부에서 궁금하지도 알 필요도 없습니다. 따라서 `plus`외 다른 메서드들은 한 클래스에 두어야한다면 `private`으로 두면 어떨까요?

추가적으로 생각해보면 좋은 것은 계산기에서 `split`을 가지고 있어야할까요?  
보통 업무개발을 할때 텍스트 처리 기능을 별도의 클래스에서 가져와서 사용하는데 그러한 점에서 
별도의 클래스를 만들어보면 어떨까요?

2022-02-03 10:27 UTC, bradley4 reviewed
요구사항이 많았는데 전반적으로 잘 지켜주셨습니다.
더 수정해보셔도 좋고, 마무리 요청을 하시면 머지하겠습니다.

2022-02-03 10:27 UTC, bradley4 commented on src/test/java/calculator/CalculatorTest.java
> +    @DisplayName("null 값을 전달하면 NullPointerException을 발생시킨다")
NIT: exception은 보통 던진다고 합니다.

2022-02-03 10:27 UTC, bradley4 commented on src/test/java/calculator/CalculatorTest.java
> +    @ValueSource(strings = {"", " "})
Junit 5.4 이상에서는 `@EmptySource` 라는 어노테이션이 있습니다.

2022-02-03 10:27 UTC, bradley4 commented on src/test/java/calculator/TextUtilTest.java
> +    void split_comma_colon_test(String input) {
👍

2022-02-03 10:27 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +        return input.substring(1, input.length() - 1);
사실 이런 부분들도 하드코딩이라고 볼 수 있습니다. 
`1, length() -1`

2022-02-03 10:27 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +                    String.format("index [%d]는 벗어난 인덱스입니다.", index)
`String.format`을 쓴게 좋네요

2022-02-03 10:27 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +        }
상황에 맞는 예외를 던지는게 좋습니다.  이런 경우는 인자가 잘못들어온 케이스가 더 맞을 것 같아요
``` suggestion 
       if(textNumbers == null) {
            throw new illegalArgumentException("Null을 전달해서는 안 됩니다.");
        }
```
> [추상화 수준에 맞는 예외를 던지라](https://velog.io/@eversong/Effective-Java-73.-%EC%B6%94%EC%83%81%ED%99%94-%EC%88%98%EC%A4%80%EC%97%90-%EB%A7%9E%EB%8A%94-%EC%98%88%EC%99%B8%EB%A5%BC-%EB%8D%98%EC%A7%80%EB%9D%BC)
> [IllgalArgumentException 문서](http://cris.joongbu.ac.kr/course/java/api/java/lang/IllegalArgumentException.html)

2022-02-03 10:27 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +public class TextUtil {
텍스트 유틸로 분리해서 책임을 나누셨군요 💯

유틸 클래스의 경우 인스턴스화를 막기 위해 `private` 생성자를 쓰곤 합니다.
> [인스턴스화를 막으려거든 private 생성자를 사용하라](https://madplay.github.io/post/enforce-noninstantiability-with-private-constructor)

2022-02-03 10:27 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +    static List<Integer> split(String textNumbers) throws NullPointerException {
여기에도 접근 제어자가 있다면 좋을 것 같습니다!

2022-02-03 10:27 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +        return result;
불필요한 변수는 제거해보면 좋을 것같아요!

2022-02-03 10:27 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +        checkException(textNumbers, regex);
Tell, don't ask 원칙이라는 글을 참고해보면 좋을 것같아요
> https://effectiveprogramming.tistory.com/entry/Tell-dont-ask

2022-02-03 10:27 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +        String regex = ",|:";
하드코딩을 제거해보면 어떨까요?

2022-02-03 10:27 UTC, bradley4 commented on src/main/java/calculator/Calculator.java
> +    }
여기도 굳이 접근 지시자를 사용하지 않을 이유는 없을 것같아요~
``` suggestion
   public int plus(String textNumbers) {
        List<Integer> numbers = split(textNumbers);
        return numbers.stream()
                .mapToInt(num -> num)
                .sum();
    }

2022-02-03 10:29 UTC, bradley4 approved these changes

2022-02-05 11:40 UTC, kkoon9 commented on src/main/java/calculator/TextUtil.java
> +public class TextUtil {
private일 경우 Test 코드를 만들 수 없게 되는데 이같은 경우에는 어떻게 해야할까요?

2022-02-05 12:09 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +public class TextUtil {
@kkoon9 
이런 고민을 하고 있는 자세가 보기 좋아요 👍

테스트를 만들고 고민하다보면 무조건 이 문제를 만나게 되는데요. 
다음 모임때 자세히 설명 드리겠습니다. 

정말 유명한 주제이기 때문에 직접 이 문제를 찾아서 해결해보고 고민한 내용을 공유해주셔도 좋을 것같아요~

2022-02-05 12:18 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +    static List<Integer> split(String textNumbers) throws IllegalArgumentException {
개인적인 궁금한 점인데, `checked exception` 처럼 `throws`를 명시하는 이유가 있을까요?
취향의 영역일 수도 있지만 코멘트를 남겨둡니다.

2022-02-05 12:32 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +        }
기존 코드를 유지하는 방향에서라면, Pattern 정도를  method로 따로 만들어두고 
`matcher.find()`로 체크할 수 있겠네요.

사실 제가 원했던 것은 원시값을 포장한 `PostiveNumber`을 객체를 만들고 객체 생성시점에 체크해서 
나의 진행 상태를 묻지않고 객체 생성을 통해 검증하는 것인데 이론적인 이야기고 산으로 가는 것같네요.  😵
이정도만 해도 충분합니다.
다만 메서드가 계속 길어지고 있는데요. 연습을 하실때는 제약을 걸어보면서 개발을 해보면 좋습니다.
클래스와 메서드의 크기를 작게 유지해보라는 권고사항이 있었던 걸로 기억하는데요. 
메서드 레벨에서 20라인이라든지 그런식의 제약을 두면서 연습을 해보면 좋습니다.

2022-02-05 12:33 UTC, merged

2022-02-05 12:34 UTC, bradley4 commented
이번 과제를 진행하시면서 개발자로서 성장하는데 조금이나마 도움이 되었기를 바랍니다.
정말 고생하셨습니다 🙇‍♂️

2022-02-05 12:39 UTC, bradley4 commented on src/main/java/calculator/TextUtil.java
> +        }
단, 제가 자세히 가이드를 드리면 학습을 진행해주시는 의미가 반감되고 
구현에 정답은 없으므로 요 방식으로 진행하셔도 될 것 같습니다!