assignment1 문자열 계산기
bradley4/tdd-calculator pull request #2
Opened 2022-02-06 11:55 UTC by lbhsos

2022-02-06 13:08 UTC, bradley4 requested changes
고생하셨습니다. 전반적으로 깔끔하게 코드를 만드셔서 읽기가 수월했습니다. 👍
몇 가지 코멘트를 남겼는데 확인 부탁드립니다. 🙇‍♂️

2022-02-06 13:08 UTC, bradley4 commented on src/test/java/study/StringTddTest.java
> +        assertThat(strArr.size()).isEqualTo(1);
같은 로직의 복합적으로 검증을 해야한다면 `assertAll()`을 찾아보고 적용해보면 어떨까요?

2022-02-06 13:08 UTC, bradley4 commented on src/test/java/study/StringTddTest.java
> +
불필요한 공백을 제거해주세요

2022-02-06 13:08 UTC, bradley4 commented on src/test/java/study/StringTddTest.java
> +
불필요하게 공백이 들어갔네요

2022-02-06 13:08 UTC, bradley4 commented on src/test/java/study/StringTddTest.java
> +    }
해당 테스트는 불필요해보입니다.

2022-02-06 13:08 UTC, bradley4 commented on src/test/java/study/CalculatorTest.java
> +
불필요하게 공백을 만드는 습관이 있네요

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +        for (int i=0; i<inputString.length(); i++) {
``` suggestion
        for (int i = 0; i < inputString.length(); i++) {
```

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +            Character curChar = inputString.charAt(i);
불필요한 축약을 안하는 연습을 해보는게 좋습니다.
`currentCharacter`로 써보면 어떨까요?

> [축약금지](https://7942yongdae.tistory.com/36)
> [클린코드02. 의미있는이름](https://velog.io/@dnr6054/Clean-Code-2-%EC%9D%98%EB%AF%B8-%EC%9E%88%EB%8A%94-%EC%9D%B4%EB%A6%84)

2022-02-06 13:08 UTC, bradley4 commented on src/test/java/calculator/StringCalculatorTest.java
> +        String givenString = "//^\\n1^-2^3^^0^^1^2^3";
`-2`를 넣어서 테스트를 하셨네요. 
다른 개발자가 보기에는 다른 케이스에 대해서도 성립하는지 궁금할 수 있습니다.
`parameterizedtest`를 찾아보고 여러가지 음수 케이스를 검증해보면 어떨까요?

2022-02-06 13:08 UTC, bradley4 commented on src/test/java/calculator/StringCalculatorTest.java
> +        String givenString = "//^\\n1^2^K^^aaKO^^1^2^3";
여기도 `parameterizedtest`를 통해 검증해보면 좋겠습니다.

2022-02-06 13:08 UTC, bradley4 commented on src/test/java/calculator/StringCalculatorTest.java
> +        String givenString = "1,2:3:0,:1,2,3";
위 테스트가 의도하는 것은 `,`에서도 작동하는지, `:`에서도 작동하는지입니다.
parameterizedtest를 통해 `1,2,3`, `1:2:3` 을 검증하는 것을 보여준다면 
해당 클래스의 테스트만 보더라도 어떤 작동이 일어날 것인지 예상하기 쉬워집니다.

2022-02-06 13:08 UTC, bradley4 commented on build.gradle
> +
추가한 이유가 있을까요? 👀

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +    private static final String END_DELIMITER = "\\n";
상수를 잘 정의해주셨습니다 💯💯

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +    public int getSum(String givenString) {
- `sum`만 해도 괜찮을 것같아요. github 소스를 검색했을때 
`sum()` 으로 검색되는 결과가 더 많았습니다.
> https://grep.app/search?q=sum%28%29&filter[lang][0]=Java

- 굳이 프로덕션 코드에서는 `주어진`같은 표현을 쓰지 않으셔도 됩니다. 
  주어진이라는 표현은 테스트에서 행위검증을 위해 사용하는 표현이라 그렇습니다.

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +        }
`givenString` 이 사용해도 안전할 거라는 보장을 할 수 있을까요?

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +        return addSeparatedNumberByDelimiter(givenString, COMMA);
절차를 나눈것이 좋습니다.

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +    private int getSumByCustomDelimiter(String givenString) {
`계산기`에서 문자를 편집하는 기능을 하고 있습니다. 계산기의 역할은 계산을 하는 것이라고 생각합니다.
SOLID의 단일 책임 원칙을 놓친것이라는 생각이 들어요. 동의하시나요?
> [단일책임원칙](https://steady-coding.tistory.com/370)

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +        String toBeSeperated = givenString.substring(endIndex+END_DELIMITER.length());
관사가 들어간 변수는 권장하지 않습니다. 참고 문서가 있으면 좋을 것같은데 해당영상밖에 없네요
> [올바른 변수 이름 짓는 법](https://www.youtube.com/watch?v=ZtkIwGZZAq8&ab_channel=%ED%8F%AC%ED%94%84TV)

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +        String[] list = givenString.split(Pattern.quote(delimiter));
- `list`보다 더 명확한 이름이면 좋지 않을까요?
- 디미터 원칙을 어기고 있네요
> [디미터 법칙](https://johngrib.github.io/wiki/law-of-demeter/)
- String을 패턴 매칭을 위해 Pattern으로 바꾸는 것은 꽤나 비싼 행위입니다. 미리 Pattern으로 만들어 사용하는 것은 어떨까요? 아래의 글을 참고하세요.
https://stackoverflow.com/questions/2469244/whats-the-difference-between-string-matches-and-matcher-matches/2469275

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +        for ( String stringNumber : list ) {
``` suggestion
        for (String stringNumber : list) {
```
불필요한 공백을 넣는 습관이 있네요!

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +            if (StringUtils.isEmpty(stringNumber)){
- 계산기의 계산기능은 도메인에 해당합니다.
현재 도메인이 `StringUtils`라는 외부기술에 노출되었네요! 
되도록이면 도메인은 외부기술에 의존하지않는 `POJO`를 지향하는 것이 좋습니다!
- 기본 자바에서 제공하는 라이브러리를 쓰지 않는 방향으로 연습한다라고 생각해도 좋습니다. 굳이 쓴다면 인터페이스로 외부기술을 감싸는 방법을 연습을 해보셔도 좋습니다.

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +            if (!StringUtils.isNumeric(stringNumber)) {
이번 연습에서는 객체지향 생활체조를 지킬 것을 권고드렸는데요.
2depth가 되었네요!

> [메서드당 들여쓰기 한번](https://developerfarm.wordpress.com/2012/01/26/object_calisthenics_2/)

2022-02-06 13:08 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +                throw new RuntimeException();
예외에는 실패한 원인을 담아주는 것이 좋습니다.
> [effective java - 예외의 상세 메시지에 실패 관련 정보를 담으라](https://jjingho.tistory.com/124)

2022-02-06 13:14 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +                throw new RuntimeException();
음수의 검증이 된 것일까요?

2022-02-06 13:16 UTC, bradley4 commented on src/test/java/calculator/StringCalculatorTest.java
> +        String givenString = "//^\\n1^-2^3^^0^^1^2^3";
`String givenString = "//^\\n1^-2^3^^0^^1^2^3";`
을 보고 다른 개발자가 음수가 들어왔을때 예외가 발생한다고 쉽게 예상할 수 있을까요?

2022-02-07 15:16 UTC, lbhsos commented on src/main/java/util/StringUtil.java
> +}
Util로 빼려다가 시간이 없어서 우선 private 함수로 빼놨습니다 ㅠ

2022-02-07 15:26 UTC, bradley4 approved these changes
의도한대로 잘 만들어주셨어요 💯

2022-02-07 15:26 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +        }
빈 텍스트일때는 어떤 값이 나와야할까요?

2022-02-07 15:26 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +        return splitByEndDelimiter[1];
1의 의미는 무엇일까요? 
> [매직넘버](https://javabom.tistory.com/28)

2022-02-07 15:26 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +        String customDelimiter = textNumbers.substring(startIndex+START_DELIMITER.length(), endIndex);
``` suggestion
        String customDelimiter = textNumbers.substring(startIndex + START_DELIMITER.length(), endIndex);
```

2022-02-07 15:26 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +                                            .collect(Collectors.toList());
좋습니다. stream을 사용해보셨군요! 👍
필터의 조건이 길어질때는 별도의 메서드를 만들고 호출하는 것이 가독성이 더 좋습니다!

2022-02-07 15:26 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +        if (!Character.isDigit(charNumber)) {
👍

2022-02-07 15:26 UTC, bradley4 commented on src/main/java/calculator/StringCalculator.java
> +            throw new RuntimeException("숫자 이외의 값 또는 음수는 전달할 수 없습니다.");
메시지에 들어간 것도 하드코딩이라고 볼 수 있습니다!

2022-02-07 15:26 UTC, bradley4 commented on src/main/java/study/StringTdd.java
> +                sb.append(currentCharacter);
기회가 되면 나중에 2depth를 줄여보는 연습을 해보는 것도 도움이 될 것같아요!

2022-02-07 15:26 UTC, bradley4 commented on src/test/java/calculator/StringCalculatorTest.java
> +    void addNumberBySeparation(String givenString) {
잘 응용하셨습니다. 이제 테스트만 보더라도 어떤 값이 테스트될지 예측하기 쉬워졌어요💯

2022-02-07 15:26 UTC, bradley4 commented on src/test/java/calculator/StringCalculatorTest.java
> +    @ValueSource(strings = {"//^\\n-1^", "//^\\n1^-7", "//^\\na^", "//^\\n1^*","//^\\n1^kk" })
음수나 숫자 이외의 값을 테스트 하기 위함이니
string에 음수를 구성하거나 특수기호로 파라미터를 넣어서 명확하게 표시해보면 더 좋을 것같습니다.

2022-02-07 15:26 UTC, bradley4 commented on src/test/java/study/StringTddTest.java
> +        );
👍

2022-02-07 15:26 UTC, bradley4 commented on src/main/java/util/StringUtil.java
> +}
나중에 시도를 🚀

2022-02-07 15:26 UTC, merged

2022-02-07 15:26 UTC, bradley4 commented
LGTM